#!/usr/bin/env python3
"""
IPsec strongSwan Configuration & Connection Manager.
Generates dynamic ipsec.conf and ipsec.secrets configurations for:
- IKEv2 and IKEv1 (Main Mode)
- Tunnel Mode vs. Transport Mode
- Native ESP vs. NAT-Traversal (forceencaps)
- Modern Ciphers (AES-GCM, AES-CBC, ChaCha20-Poly1305)
- Legacy/Weak Ciphers (3DES, DES, MD5, SHA1)
- DH Groups (1, 2, 5, 14, 19, 20, 21)
- Perfect Forward Secrecy (PFS) enabled/disabled
"""

import subprocess
import argparse
import time
import sys
import os

PSK_SECRET = "NTRO_SIH26_SUPER_SECRET_KEY_2026"

def run_cmd(cmd):
    """Executes a shell command."""
    res = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    return res.returncode == 0, res.stdout, res.stderr

def configure_secrets():
    """Writes pre-shared key into /etc/ipsec.secrets."""
    with open("/etc/ipsec.secrets", "w") as f:
        f.write(f': PSK "{PSK_SECRET}"\n')
    os.chmod("/etc/ipsec.secrets", 0o600)

def generate_ipsec_conf(role, ike_version="ikev2", mode="tunnel", 
                        ike_cipher="aes256gcm16-prfsha256-ecp256",
                        esp_cipher="aes256gcm16-ecp256",
                        nat_t=False):
    """
    Generates and writes /etc/ipsec.conf tailored to role ('initiator' or 'responder').
    """
    left_ip = "172.28.0.2"
    right_ip = "172.28.0.3"
    
    force_encap = "yes" if nat_t else "no"
    
    # Subnets depending on mode
    if mode == "tunnel":
        left_sub = "172.28.0.2/32"
        right_sub = "172.28.0.3/32"
    else: # transport
        left_sub = "%dynamic"
        right_sub = "%dynamic"

    conf_content = f"""# Automatically generated by SIH26 IPsec Testbed Engine
config setup
    charondebug="ike 2, knl 2, cfg 2, esp 2"
    uniqueids=no

conn %default
    keyingtries=%forever
    authby=secret
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s

conn vpn-link
    left={left_ip}
    right={right_ip}
    leftsubnet={left_sub}
    rightsubnet={right_sub}
    keyexchange={ike_version}
    type={mode}
    ike={ike_cipher}!
    esp={esp_cipher}!
    forceencaps={force_encap}
    auto=add
"""

    with open("/etc/ipsec.conf", "w") as f:
        f.write(conf_content)
    print(f"[{role.capitalize()}] Wrote /etc/ipsec.conf for {ike_version}, {mode}, IKE:{ike_cipher}, ESP:{esp_cipher}")

def restart_strongswan():
    """Flushes existing kernel SAs and restarts strongSwan."""
    run_cmd("ipsec down vpn-link 2>/dev/null")
    run_cmd("ipsec stop 2>/dev/null")
    run_cmd("ip xfrm state flush 2>/dev/null")
    run_cmd("ip xfrm policy flush 2>/dev/null")
    time.sleep(1)
    ok, out, err = run_cmd("ipsec start")
    time.sleep(1.5)
    return ok

def bring_up_tunnel():
    """Initiates the IPsec connection."""
    print("[Initiator] Bringing up tunnel 'vpn-link'...")
    ok, out, err = run_cmd("ipsec up vpn-link")
    print(out)
    # Check if SA is installed in kernel
    ok, status_out, _ = run_cmd("ipsec status vpn-link")
    if "ESTABLISHED" in status_out or "INSTALLED" in status_out:
        print("[Initiator] Tunnel successfully established!")
        return True
    return False

def bring_down_tunnel():
    """Terminates active connections and flushes kernel states."""
    run_cmd("ipsec down vpn-link 2>/dev/null")
    run_cmd("ipsec stop 2>/dev/null")
    run_cmd("ip xfrm state flush 2>/dev/null")
    run_cmd("ip xfrm policy flush 2>/dev/null")


def main():
    parser = argparse.ArgumentParser(description="strongSwan IPsec Manager")
    parser.add_argument("--role", choices=["initiator", "responder"], required=True)
    parser.add_argument("--action", choices=["setup", "start", "stop", "status"], default="setup")
    parser.add_argument("--ike-version", choices=["ikev2", "ikev1"], default="ikev2")
    parser.add_argument("--mode", choices=["tunnel", "transport"], default="tunnel")
    parser.add_argument("--ike-cipher", default="aes256gcm16-prfsha256-ecp256")
    parser.add_argument("--esp-cipher", default="aes256gcm16-ecp256")
    parser.add_argument("--nat-t", action="store_true")

    args = parser.parse_args()

    if args.action == "stop":
        bring_down_tunnel()
        return

    if args.action == "status":
        _, out, _ = run_cmd("ipsec statusall")
        print(out)
        return

    # Setup configuration
    configure_secrets()
    generate_ipsec_conf(
        role=args.role,
        ike_version=args.ike_version,
        mode=args.mode,
        ike_cipher=args.ike_cipher,
        esp_cipher=args.esp_cipher,
        nat_t=args.nat_t
    )
    restart_strongswan()

    if args.role == "initiator" and args.action == "start":
        bring_up_tunnel()

if __name__ == "__main__":
    main()
